# Generated by Django 2.2.24 on 2021-06-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevelopInfo',
            new_name='Develop_Info',
        ),
    ]
