# Generated by Django 2.2.24 on 2021-06-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0002_auto_20210622_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Develop_Info',
            new_name='Develop_Test_Info',
        ),
    ]
