# Generated by Django 3.1 on 2021-06-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(blank=True, default='article/default2.jpg', max_length=200, null=True, upload_to='article/%y/%m/%d', verbose_name='封面'),
        ),
    ]
