# Generated by Django 3.1 on 2021-07-03 12:36

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210701_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(blank=True, default='None', max_length=200, null=True, upload_to='upfile/', verbose_name='封面'),
        ),
    ]
