# Generated by Django 3.1 on 2021-07-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210703_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='taginfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.taginfo', verbose_name='所属标签'),
        ),
    ]
