# Generated by Django 3.1 on 2021-07-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articleinfo_taginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.category', verbose_name='所属类别'),
        ),
    ]
